In [4]:
from pandas import DataFrame, Series
import pandas as pd

#시리즈 객체 생성
myCampus = Series(data=[100,200,300,400,500], 
index=["2026-09-15", "2026-09-16", "2026-09-17", 
       "2026-09-18", "2026-09-19"])

#슬라이싱
myCampus["2026-09-16"]
#셀단위: shift + enter

np.int64(200)

In [9]:
#딕셔너리를 데이터프레임으로 변환
data = {"foreigner":[1,2,3,4,5,6],
        "sratio":[10,20,30,40,50,60], 
        "org":[100,200,300,400,500,600], 
        "sprice":[1,2,3,4,5,6], 
        "private":[10,20,30,40,50,60]
        }

df = DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   foreigner  6 non-null      int64
 1   sratio     6 non-null      int64
 2   org        6 non-null      int64
 3   sprice     6 non-null      int64
 4   private    6 non-null      int64
dtypes: int64(5)
memory usage: 372.0 bytes

In [11]:
#컬럼을 순서를 지정 
df2 = DataFrame(data=data, 
    columns=["private","org","foreigner","sratio","sprice"],
    index=["2026-09-15","2026-09-16","2026-09-17",
           "2026-09-18","2026-09-19","2026-09-20"])

df2

            private  org  foreigner  sratio  sprice
2026-09-15       10  100          1      10       1
2026-09-16       20  200          2      20       2
2026-09-17       30  300          3      30       3
2026-09-18       40  400          4      40       4
2026-09-19       50  500          5      50       5
2026-09-20       60  600          6      60       6

In [13]:
#특정컬럼만 슬라이싱
df2["org"]

2026-09-15    100
2026-09-16    200
2026-09-17    300
2026-09-18    400
2026-09-19    500
2026-09-20    600
Name: org, dtype: int64

In [15]:
#특정행을 슬라이싱: .loc (location)
df2.loc["2026-09-16"]

private       20
org          200
foreigner      2
sratio        20
sprice         2
Name: 2026-09-16, dtype: int64

In [17]:
#피봇팅
df2.T 
df2.transpose()

,2026-09-15,2026-09-16,2026-09-17,2026-09-18,2026-09-19,2026-09-20
private,10,20,30,40,50,60
org,100,200,300,400,500,600
foreigner,1,2,3,4,5,6
sratio,10,20,30,40,50,60
sprice,1,2,3,4,5,6

In [18]:
#파일에서 Dataframe으로 로딩
!type c:\work\ex1.csv

id, name, price, description
1, iphone, 1990000, iphone 17
2, android, 1590000, samsung phone
3, winphone, 850000, microsoft winphone

In [19]:
data1 = pd.read_csv("c:\\work\\ex1.csv")
data1

   id       name    price           description
0   1     iphone  1990000            iphone 17
1   2    android  1590000         samsung phone
2   3   winphone   850000   microsoft winphone

In [20]:
!type c:\work\ex2.csv

1, iphone, 1990000, iphone 17
2, android, 1590000, samsung phone
3, winphone, 850000, microsoft winphone

In [22]:
data2 = pd.read_csv("c:\\work\\ex2.csv", 
    names=["id","name","price","desc"])
data2

   id       name    price                  desc
0   1     iphone  1990000            iphone 17
1   2    android  1590000         samsung phone
2   3   winphone   850000   microsoft winphone

In [23]:
!type c:\work\ex3.txt

data1 data2 data3
1.2     2.3     1.3
0.1     1.5     2.5
3.1     3.2     3.3

In [ ]:
#특수문자 r: raw string notation 
data3 = pd.read_table(r"c:\work\ex3.txt", sep=r"\s+")
data3

   data1  data2  data3
0    1.2    2.3    1.3
1    0.1    1.5    2.5
2    3.1    3.2    3.3